ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"
MONGODB_USERNAME: "user"
MONGODB_PASSWORD: "FsXgd9IPyfHdMh24"
MONGODB_HOST: "localhost"
MONGODB_PORT: '27017'
MONGODB_DB: "tevkil"
MONGODB_RS: "rs1"
MONGODB_URI: "mongodb+srv://user:FsXgd9IPyfHdMh24@java.84pxyo6.mongodb.net/"
PASSWORD: "8c9fe331-2d80-4c75-960a-9823a858ed54"
SECRET_KEY: "5df6c33d7420707dab95f853538374073b776e71ac9767af5ab70e62fd921cba"