spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}
  application:
    jwt:
      access-secret: ${ACCESS_SECRET_KEY}
      refresh-secret: ${REFRESH_SECRET_KEY}
logging:
  level:
    org.springframework.security: DEBUG